const express=require('express'),http=require('http'),path=require('path'),crypto=require('crypto'),{Server}=require('socket.io'),{MongoClient}=require('mongodb');
const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.static(path.join(__dirname,'public')));const PORT=process.env.PORT||3000,URI=process.env.MONGODB_URI,ACCESS='112211',TTL=90*24*60*60*1000;
let dbi,accounts,messages,groups,readStates;const online=new Map();const mem={accounts:new Map(),messages:[],groups:new Map(),read:new Map()};
async function init(){if(!URI){console.warn('MONGODB_URI missing; data persists only while server is running');return}const c=new MongoClient(URI);await c.connect();dbi=c.db(process.env.MONGODB_DB||'fivechat');accounts=dbi.collection('accounts');messages=dbi.collection('messages');groups=dbi.collection('groups');readStates=dbi.collection('readStates');await accounts.createIndex({nameLower:1},{unique:true});await messages.createIndex({time:1},{expireAfterSeconds:TTL});await messages.createIndex({kind:1,chatKey:1,time:1});await groups.createIndex({id:1},{unique:true});await readStates.createIndex({key:1},{unique:true});console.log('MongoDB connected')}
async function allPeople(){if(accounts){const a=await accounts.find({}, {projection:{_id:0,name:1,createdAt:1,lastSeen:1,avatar:1,nameLower:1}}).sort({name:1}).toArray();return a.map(x=>({...x,online:online.has(x.nameLower)}))}return [...mem.accounts.values()].map(x=>({...x,online:online.has(x.nameLower)})).sort((a,b)=>a.name.localeCompare(b.name))}
async function emitPeople(){io.to('main').emit('people',await allPeople())}function pair(a,b){return[a.toLowerCase(),b.toLowerCase()].sort().join('::')}async function history(kind,key){return messages?messages.find({kind,chatKey:key},{projection:{_id:0}}).sort({time:1}).toArray():mem.messages.filter(m=>m.kind===kind&&m.chatKey===key).sort((a,b)=>a.time-b.time)}async function save(m){if(messages)await messages.insertOne(m);else mem.messages.push(m)}async function account(name){return accounts?accounts.findOne({nameLower:name.toLowerCase()}):mem.accounts.get(name.toLowerCase())}function pinHash(pin){return crypto.createHash('sha256').update(String(pin)).digest('hex')}
async function createAccount(name,pin){const key=name.toLowerCase(),obj={name,nameLower:key,pinHash:pinHash(pin),createdAt:Date.now(),lastSeen:Date.now(),avatar:name[0].toUpperCase()};if(accounts){if(await accounts.findOne({nameLower:key}))return {error:'Name already exists. Try a new name.'};try{await accounts.insertOne(obj);return obj}catch(e){if(e.code===11000)return {error:'Name already exists. Try a new name.'};throw e}}if(mem.accounts.has(key))return {error:'Name already exists. Try a new name.'};mem.accounts.set(key,obj);return obj}
async function groupsFor(name){return groups?groups.find({membersLower:name.toLowerCase()},{projection:{_id:0}}).sort({updatedAt:-1}).toArray():[...mem.groups.values()].filter(g=>g.membersLower.includes(name.toLowerCase())).sort((a,b)=>b.updatedAt-a.updatedAt)}async function getReadAt(user,key){const k=user.toLowerCase()+'::'+key;if(readStates){const r=await readStates.findOne({key:k});return r?.time||0}return mem.read.get(k)||0}async function markRead(user,kind,key){const k=user.toLowerCase()+'::'+key,t=Date.now();if(readStates)await readStates.updateOne({key:k},{$set:{key:k,user:user.toLowerCase(),kind,chatKey:key,time:t}},{upsert:true});else mem.read.set(k,t)}
async function unreadSummary(name,gs){const out={};const me=name.toLowerCase();if(messages){const dm=await messages.find({kind:'direct',time:{$gte:Date.now()-TTL},to:name},{projection:{_id:0,from:1,to:1,time:1,chatKey:1}}).sort({time:1}).limit(5000).toArray();for(const m of dm){if(m.from.toLowerCase()===me)continue;const read=await getReadAt(name,m.chatKey);if(m.time>read){const k='direct:'+m.from.toLowerCase();out[k]=(out[k]||0)+1}}const gids=gs.map(g=>g.id);if(gids.length){const gm=await messages.find({kind:'group',groupId:{$in:gids},time:{$gte:Date.now()-TTL}},{projection:{_id:0,groupId:1,from:1,time:1}}).toArray();for(const m of gm){if(m.from.toLowerCase()===me)continue;const read=await getReadAt(name,m.groupId);if(m.time>read){const k='group:'+m.groupId;out[k]=(out[k]||0)+1}}}}else for(const m of mem.messages){if(m.time<Date.now()-TTL||m.from.toLowerCase()===me)continue;if(m.kind==='direct'&&m.to.toLowerCase()===me&&m.time>(mem.read.get(me+'::'+m.chatKey)||0)){const k='direct:'+m.from.toLowerCase();out[k]=(out[k]||0)+1}else if(m.kind==='group'){const g=gs.find(x=>x.id===m.groupId);if(g&&m.time>(mem.read.get(me+'::'+m.groupId)||0)){const k='group:'+m.groupId;out[k]=(out[k]||0)+1}}}return out}
function cleanAttachment(a){if(!a||typeof a!=='object')return null;const name=String(a.name||'').slice(0,120),type=String(a.type||'').slice(0,100),data=String(a.data||'');if(!name||!type||!data||data.length>8*1024*1024)return null;if(!/^data:(image\/|application\/pdf|text\/|application\/(msword|vnd.openxmlformats-officedocument|vnd.ms-|octet-stream))/.test(data))return null;return{name,type,data}}
io.on('connection',s=>{s.on('createAccount',async p=>{const name=String(p?.name||'').trim().slice(0,30),pin=String(p?.pin||'').trim(),code=String(p?.accessCode||'').trim();if(!name||!/^[0-9]{4}$/.test(pin)||code!==ACCESS)return s.emit('authError',code!==ACCESS?'Incorrect access code.':(!name?'Enter your name.':'Enter a valid 4-digit PIN.'));const a=await createAccount(name,pin);if(a.error)return s.emit('authError',a.error);s.emit('accountCreated',{name:a.name})});
s.on('login',async p=>{const name=String(p?.name||'').trim().slice(0,30),pin=String(p?.pin||'').trim();if(!name||!/^[0-9]{4}$/.test(pin))return s.emit('authError','Enter your name and 4-digit PIN.');const a=await account(name);if(!a)return s.emit('authError','Account not found. Please sign up first.');if(a.pinHash!==pinHash(pin))return s.emit('authError','Incorrect PIN.');if(online.has(name.toLowerCase())){const old=online.get(name.toLowerCase());const os=io.sockets.sockets.get(old.socketId);if(os)os.disconnect(true)}s.join('main');s.data.userName=a.name;s.data.nameLower=name.toLowerCase();online.set(name.toLowerCase(),{name:a.name,socketId:s.id});if(accounts)await accounts.updateOne({nameLower:name.toLowerCase()},{$set:{lastSeen:Date.now()}});const gs=await groupsFor(a.name);s.emit('loggedIn',{user:a,people:await allPeople(),groups:gs,unread:await unreadSummary(a.name,gs)});await emitPeople()});
s.on('markRead',async p=>{const n=s.data.userName;if(!n)return;if(p?.kind==='direct'&&p?.with)await markRead(n,'direct',pair(n,p.with));if(p?.kind==='group'&&p?.groupId)await markRead(n,'group',String(p.groupId))});s.on('openDirect',async p=>{const a=s.data.userName,b=String(p?.with||'').trim();if(a&&b&&a.toLowerCase()!==b.toLowerCase())s.emit('directHistory',{with:b,messages:await history('direct',pair(a,b))})});
s.on('sendDirect',async p=>{const from=s.data.userName,to=String(p?.to||'').trim().slice(0,30),text=String(p?.text||'').trim().slice(0,2000),attachment=cleanAttachment(p?.attachment);if(!from||!to||(!text&&!attachment))return;const m={id:Date.now()+'-'+Math.random().toString(36).slice(2),kind:'direct',chatKey:pair(from,to),from,to,text,attachment,time:Date.now()};await save(m);io.to('main').emit('directMessage',m)});
s.on('createGroup',async p=>{const name=String(p?.name||'').trim().slice(0,50),list=Array.isArray(p?.members)?p.members.map(x=>String(x).trim().slice(0,30)).filter(Boolean):[],me=s.data.userName;if(!me||!name)return;const members=[...new Set([me,...list])],id=Date.now()+'-'+Math.random().toString(36).slice(2),g={id,name,createdBy:me,members,membersLower:members.map(x=>x.toLowerCase()),createdAt:Date.now(),updatedAt:Date.now()};if(groups)await groups.insertOne(g);else mem.groups.set(id,g);for(const member of members){const target=[...io.sockets.sockets.values()].find(x=>x.data.userName?.toLowerCase()===member.toLowerCase());if(target)target.emit('groupCreated',g)}s.emit('groupCreated',g)});
s.on('openGroup',async p=>{const id=String(p?.id||''),gs=await groupsFor(s.data.userName),g=gs.find(x=>x.id===id);if(g)s.emit('groupHistory',{group:g,messages:await history('group',id)})});s.on('sendGroup',async p=>{const id=String(p?.groupId||''),text=String(p?.text||'').trim().slice(0,2000),attachment=cleanAttachment(p?.attachment),me=s.data.userName,gs=await groupsFor(me),g=gs.find(x=>x.id===id);if(!g||(!text&&!attachment))return;const m={id:Date.now()+'-'+Math.random().toString(36).slice(2),kind:'group',chatKey:id,groupId:id,from:me,text,attachment,time:Date.now()};await save(m);if(groups)await groups.updateOne({id},{$set:{updatedAt:m.time}});else g.updatedAt=m.time;for(const [sock] of io.sockets.sockets)if(g.membersLower.includes(sock.data.userName?.toLowerCase()))sock.emit('groupMessage',m)});
s.on('typing',p=>{const to=String(p?.to||'');if(to)s.to('main').emit('typing',{from:s.data.userName,to})});s.on('stopTyping',p=>{const to=String(p?.to||'');if(to)s.to('main').emit('stopTyping',{from:s.data.userName,to})});s.on('logout',()=>offline(s));s.on('disconnect',()=>offline(s))});
async function offline(s){const key=s.data.nameLower;if(!key)return;const x=online.get(key);if(x?.socketId===s.id)online.delete(key);if(accounts)await accounts.updateOne({nameLower:key},{$set:{lastSeen:Date.now()}});await emitPeople();delete s.data.userName;delete s.data.nameLower}
init().then(()=>server.listen(PORT,()=>console.log('FiveChat v24 on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
