const express=require('express'),http=require('http'),path=require('path'),crypto=require('crypto'),{Server}=require('socket.io'),{MongoClient}=require('mongodb');
const app=express(),server=http.createServer(app),io=new Server(server,{maxHttpBufferSize:10*1024*1024});app.use(express.static(path.join(__dirname,'public')));
const PORT=process.env.PORT||3000,URI=process.env.MONGODB_URI,ACCESS='112211',ROOM='main',TTL=90*24*60*60*1000,MAX=1000;
let dbi,accounts,messages,groups;const MAX_ATTACHMENT=5*1024*1024;const online=new Map();const mem={accounts:new Map(),messages:[],groups:new Map()};
async function init(){if(!URI){console.warn('MONGODB_URI missing; data persists only while server is running');return}const c=new MongoClient(URI);await c.connect();dbi=c.db(process.env.MONGODB_DB||'fivechat');accounts=dbi.collection('accounts');messages=dbi.collection('messages');groups=dbi.collection('groups');await accounts.createIndex({nameLower:1},{unique:true});await messages.createIndex({time:1},{expireAfterSeconds:TTL});await messages.createIndex({kind:1,chatKey:1,time:1});await groups.createIndex({id:1},{unique:true});console.log('MongoDB connected')}
function roomUsers(){return [...online.values()].map(x=>({name:x.name,online:true}));}
async function allPeople(){if(accounts){const a=await accounts.find({}, {projection:{_id:0,name:1,nameLower:1,createdAt:1,lastSeen:1,online:1,avatar:1}}).sort({name:1}).toArray();return a.map(x=>({...x,online:online.has(x.nameLower)}))}return [...mem.accounts.values()].map(x=>({...x,online:online.has(x.nameLower)})).sort((a,b)=>a.name.localeCompare(b.name))}
async function emitPeople(){io.to(ROOM).emit('people',await allPeople())}
function pair(a,b){return [a.toLowerCase(),b.toLowerCase()].sort().join('::')}
async function history(kind,key){if(messages)return messages.find({kind,chatKey:key},{projection:{_id:0}}).sort({time:1}).toArray();return mem.messages.filter(m=>m.kind===kind&&m.chatKey===key).sort((a,b)=>a.time-b.time)}
async function save(m){if(messages)await messages.insertOne(m);else mem.messages.push(m)}
async function account(name){if(accounts)return accounts.findOne({nameLower:name.toLowerCase()},{projection:{_id:0,name:1,nameLower:1,pinHash:1,createdAt:1,lastSeen:1,avatar:1}});return mem.accounts.get(name.toLowerCase())}
async function createAccount(name,pin){const key=name.toLowerCase();const obj={name, nameLower:key, pinHash:pinHash(pin), createdAt:Date.now(), lastSeen:Date.now(), avatar:name[0].toUpperCase()};if(accounts){try{await accounts.insertOne(obj);return obj}catch(e){return null}}if(mem.accounts.has(key))return null;mem.accounts.set(key,obj);return obj}
async function groupsFor(name){if(groups)return groups.find({membersLower:name.toLowerCase()},{projection:{_id:0}}).sort({updatedAt:-1}).toArray();return [...mem.groups.values()].filter(g=>g.membersLower.includes(name.toLowerCase())).sort((a,b)=>b.updatedAt-a.updatedAt)}
function onlineMap(){return online}
function safeAttachments(list){if(!Array.isArray(list))return[];return list.slice(0,6).filter(a=>a&&typeof a.name==='string'&&typeof a.data==='string'&&a.data.length<MAX_ATTACHMENT*1.4).map(a=>({name:String(a.name).slice(0,160),type:String(a.type||'application/octet-stream').slice(0,120),size:Math.min(Number(a.size)||0,MAX_ATTACHMENT),data:a.data}))}
function pinHash(pin){return crypto.createHash('sha256').update(String(pin)).digest('hex')}
io.on('connection',s=>{
 s.on('createAccount',async p=>{const name=String(p?.name||'').trim().slice(0,30),pin=String(p?.pin||'').trim(),code=String(p?.accessCode||'').trim();if(!name||!/^[0-9]{4}$/.test(pin)||code!==ACCESS)return s.emit('authError',code!==ACCESS?'Incorrect access code.':(!name?'Enter your name.':'Enter a valid 4-digit PIN.'));const a=await createAccount(name,pin);if(!a)return s.emit('authError','Name already exists. Try a new name.');s.emit('accountCreated',{name:a.name});});
 s.on('login',async p=>{const name=String(p?.name||'').trim().slice(0,30),pin=String(p?.pin||'').trim();if(!name||!/^[0-9]{4}$/.test(pin))return s.emit('authError','Enter your name and 4-digit PIN.');const a=await account(name);if(!a)return s.emit('authError','Account not found. Please create an account first.');if(a.pinHash!==pinHash(pin))return s.emit('authError','Incorrect 4-digit PIN.');if(online.has(name.toLowerCase())){const old=online.get(name.toLowerCase());const os=io.sockets.sockets.get(old.socketId);if(os)os.disconnect(true)}s.join(ROOM);s.data.userName=a.name;s.data.nameLower=name.toLowerCase();online.set(name.toLowerCase(),{name:a.name,socketId:s.id});if(accounts)await accounts.updateOne({nameLower:name.toLowerCase()},{$set:{online:true,lastSeen:Date.now()}});const user={name:a.name,createdAt:a.createdAt,lastSeen:a.lastSeen,avatar:a.avatar};s.emit('loggedIn',{user,people:await allPeople(),groups:await groupsFor(a.name),unread:{}});await emitPeople()});
 s.on('openDirect',async p=>{const a=s.data.userName,b=String(p?.with||'').trim();if(!a||!b||a.toLowerCase()===b.toLowerCase())return;s.emit('directHistory',{with:b,messages:await history('direct',pair(a,b))})});
 s.on('sendDirect',async p=>{const from=s.data.userName,to=String(p?.to||'').trim().slice(0,30),text=String(p?.text||'').trim().slice(0,2000);if(!from||!to||!text)return;const attachments=safeAttachments(p?.attachments);const m={id:Date.now()+'-'+Math.random().toString(36).slice(2),kind:'direct',chatKey:pair(from,to),from,to,text,attachments,time:Date.now()};await save(m);io.to(ROOM).emit('directMessage',m)});
 s.on('createGroup',async p=>{const name=String(p?.name||'').trim().slice(0,50),list=Array.isArray(p?.members)?p.members.map(x=>String(x).trim().slice(0,30)).filter(Boolean):[];const me=s.data.userName;if(!me||!name)return;const members=[...new Set([me,...list])];const id=Date.now()+'-'+Math.random().toString(36).slice(2);const g={id,name,createdBy:me,members,membersLower:members.map(x=>x.toLowerCase()),createdAt:Date.now(),updatedAt:Date.now()};if(groups)await groups.insertOne(g);else mem.groups.set(id,g);for(const member of members){const target=[...io.sockets.sockets.values()].find(x=>x.data.userName?.toLowerCase()===member.toLowerCase());if(target)target.emit('groupCreated',g)}s.emit('groupCreated',g)});
 s.on('openGroup',async p=>{const id=String(p?.id||'');const gs=await groupsFor(s.data.userName);const g=gs.find(x=>x.id===id);if(!g)return;s.emit('groupHistory',{group:g,messages:await history('group',id)})});
 s.on('sendGroup',async p=>{const id=String(p?.groupId||''),text=String(p?.text||'').trim().slice(0,2000),me=s.data.userName;const gs=await groupsFor(me),g=gs.find(x=>x.id===id);if(!g||!text)return;const attachments=safeAttachments(p?.attachments);const m={id:Date.now()+'-'+Math.random().toString(36).slice(2),kind:'group',chatKey:id,groupId:id,from:me,text,attachments,time:Date.now()};await save(m);if(groups)await groups.updateOne({id},{$set:{updatedAt:m.time}});else g.updatedAt=m.time;for(const [sock] of io.sockets.sockets){if(g.membersLower.includes(sock.data.userName?.toLowerCase()))sock.emit('groupMessage',m)}});
 s.on('typing',p=>{const to=String(p?.to||'');if(to)s.to(ROOM).emit('typing',{from:s.data.userName,to})});s.on('stopTyping',p=>{const to=String(p?.to||'');if(to)s.to(ROOM).emit('stopTyping',{from:s.data.userName,to})});
 s.on('logout',()=>offline(s));s.on('disconnect',()=>offline(s));
});
async function offline(s){const n=s.data.userName,key=s.data.nameLower;if(!n||!key)return;const x=online.get(key);if(x?.socketId===s.id)online.delete(key);if(accounts)await accounts.updateOne({nameLower:key},{$set:{online:false,lastSeen:Date.now()}});await emitPeople();delete s.data.userName;delete s.data.nameLower}
init().then(()=>server.listen(PORT,()=>console.log('FiveChat v13 on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
