const express=require("express"),http=require("http"),path=require("path"),{Server}=require("socket.io"),{MongoClient}=require("mongodb");
const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.static(path.join(__dirname,"public")));
const PORT=process.env.PORT||3000,MAX=5,TTL=24*60*60*1000,URI=process.env.MONGODB_URI;
let col=null;const rooms=new Map();
async function db(){if(!URI){console.warn("MONGODB_URI missing");return}const c=new MongoClient(URI);await c.connect();const d=c.db(process.env.MONGODB_DB||"fivechat");col=d.collection("messages");await col.createIndex({time:1},{expireAfterSeconds:TTL});await col.createIndex({roomName:1,time:1});console.log("MongoDB connected")}
function room(n){if(!rooms.has(n))rooms.set(n,new Map());return rooms.get(n)}
async function history(n){return col?await col.find({roomName:n,time:{$gte:Date.now()-TTL}},{projection:{_id:0,roomName:0}}).sort({time:1}).toArray():[]}
io.on("connection",s=>{
s.on("joinRoom",async({roomName,userName})=>{try{roomName=String(roomName||"").trim().slice(0,40);userName=String(userName||"").trim().slice(0,30);if(!roomName||!userName)return s.emit("joinError","Enter your name and room name.");let r=room(roomName);if(r.size>=MAX)return s.emit("joinError","This room already has 5 members.");if([...r.values()].some(x=>x.name.toLowerCase()==userName.toLowerCase()))return s.emit("joinError","That name is already used.");s.join(roomName);r.set(s.id,{name:userName});s.data.roomName=roomName;s.data.userName=userName;let list=[...r.values()].map(x=>({name:x.name,online:true}));s.emit("joined",{roomName,userName,messages:await history(roomName),users:list});io.to(roomName).emit("members",list)}catch(e){console.error(e);s.emit("joinError","Unable to join.")}});
s.on("sendMessage",async text=>{let n=s.data.roomName,u=s.data.userName;if(!n||!u)return;text=String(text||"").trim().slice(0,2000);if(!text)return;let m={id:Date.now()+"-"+Math.random().toString(36).slice(2),roomName:n,name:u,text,time:Date.now()};try{if(col)await col.insertOne(m);delete m.roomName;io.to(n).emit("message",m)}catch(e){s.emit("sendError","Message was not saved. Try again.")}});
s.on("typing",()=>s.data.roomName&&s.to(s.data.roomName).emit("typing",s.data.userName));s.on("stopTyping",()=>s.data.roomName&&s.to(s.data.roomName).emit("stopTyping"));
s.on("disconnect",()=>{let n=s.data.roomName;if(!n||!rooms.has(n))return;let r=rooms.get(n);r.delete(s.id);io.to(n).emit("members",[...r.values()].map(x=>({name:x.name,online:true})));if(!r.size)rooms.delete(n)})});
db().then(()=>server.listen(PORT,()=>console.log("FiveChat on "+PORT))).catch(e=>{console.error(e);process.exit(1)})